name: Chrome headless
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e:ci --env circle=true 
          browser: chrome
          headless: true
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: tests/e2e/videos
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-screenshots
          path: tests/e2e/screenshots
